### ISSUE TITLE
有一种PS流解析不了，希望增加支持

### ISSUE THREAD

**Issue by MagiciSource** [hongch911/WiresharkPlugin#1]
非常好用的插件，感谢作者，提交个问题，有一种PS流解析不了，希望可以增加支持。
这种PS流的00 00 01的头和后面的载荷连在一起，具体如图
![IMG_20201005_095422](https://user-images.githubusercontent.com/15188279/95033449-ef33d000-06f0-11eb-8b74-3ec0f11b9276.jpg)

**Comment by hongch911** [comment]
重新处理了ps流的解析。

**Comment by ChungTak** [comment]
MagiciSource @hongch911   请教插件怎样用的？ 插件都成功加载，编辑-》选项-》协议 -> ps -> dynic payload type设置为96。抓包信息右键 解码为(decode as ..) 当前设置为RTP
结果还是只能解析到RTP这层，没有上图中的PS层。
请问还需要设置什么？wireshark 2.6 3.0 3.2我都装过了一遍，还是没解决

**Comment by MagiciSource** [comment]
> MagiciSource @hongch911 请教插件怎样用的？ 插件都成功加载，编辑-》选项-》协议 -> ps -> dynic payload type设置为96。抓包信息右键 解码为(decode as ..) 当前设置为RTP
> 结果还是只能解析到RTP这层，没有上图中的PS层。
> 请问还需要设置什么？wireshark 2.6 3.0 3.2我都装过了一遍，还是没解决

你确定你收到的流payload是96么？你还可以试着把rtp解码为ps

**Comment by ChungTak** [comment]
感谢你的回复～～确定收到的流payload是96, ～ “你还可以试着把rtp解码为ps”  ，请问rtp解码为ps 这部怎样操作？我对wireshark不太熟悉，我右键 解码为(decode as ..) 当前设置只能设置为RTP,下拉列表里面没有 ps选项

**Comment by MagiciSource** [comment]
> 感谢你的回复～～确定收到的流payload是96, ～ “你还可以试着把rtp解码为ps” ，请问rtp解码为ps 这部怎样操作？我对wireshark不太熟悉，我右键 解码为(decode as ..) 当前设置只能设置为RTP,下拉列表里面没有 ps选项

**Comment by MagiciSource** [comment]
> 感谢你的回复～～确定收到的流payload是96, ～ “你还可以试着把rtp解码为ps” ，请问rtp解码为ps 这部怎样操作？我对wireshark不太熟悉，我右键 解码为(decode as ..) 当前设置只能设置为RTP,下拉列表里面没有 ps选项


我用的3.2.4

**Comment by MagiciSource** [comment]
> 感谢你的回复～～确定收到的流payload是96, ～ “你还可以试着把rtp解码为ps” ，请问rtp解码为ps 这部怎样操作？我对wireshark不太熟悉，我右键 解码为(decode as ..) 当前设置只能设置为RTP,下拉列表里面没有 ps选项

![IMG_20201015_122833](https://user-images.githubusercontent.com/15188279/96077317-0d17e680-0ee2-11eb-8d01-35ff1717d041.jpg)

**Comment by ChungTak** [comment]
按你的方法可以～～谢谢!

**Comment by MagiciSource** [comment]
@ChungTak 没事，你也要搞媒体收发么，可以多交流

**Comment by ChungTak** [comment]
新手~在学国标的东西～～～

**Comment by MagiciSource** [comment]
@hongch911 
新版的插件解析不了以前那种单独发PS头的流了，上一版的插件可以正常解析
![IMG_20201019_105155](https://user-images.githubusercontent.com/15188279/96396243-55dce180-11f9-11eb-8fa3-fbff41f38584.jpg)
