### ISSUE TITLE
最新插件不能正常解析PS流

### ISSUE THREAD

**Issue by MagiciSource** [hongch911/WiresharkPlugin#2]
最新版的插件解析不了之前可以正常解析的PS流了，就是那种单独发PS头的流
![IMG_20201019_105155](https://user-images.githubusercontent.com/15188279/97509838-4c543600-19be-11eb-804c-3cc280c15e05.jpg)

**Comment by hongch911** [comment]
最新的插件，是把多个RTP数据包组装成的一帧完整的ps数据后，在最后一个RTP里面单独解析。所以看着感觉前面的RTP数据包没有解析。

**Comment by MagiciSource** [comment]
这样显示解析之后看起来有点奇怪😂，有多个流待解析的时候，不好区分这一包是不是已经解析过了

**Comment by hongch911** [comment]
方便给个没有敏感信息的抓包文件，我试试吗？可以邮箱发给我 hongch_911@126.com

**Comment by MagiciSource** [comment]
已发送，前几天没在单位，不好意思

**Comment by hongch911** [comment]
PS解析包，会组合好完整的一个ps数据包后，才解析。所以看着感觉有些RTP包没有解析似的。因为PS的一次数据包不完整，就没有每一个RTP数据包都解析。
