### ISSUE TITLE
rtp_h265_export.lua加载时报错

### ISSUE THREAD

**Issue by liuchen1206** [hongch911/WiresharkPlugin#4]
wireshark（v2.6.6-0-gdf942cd8）版本启动时加载rtp_h265_export.lua时会报错，具体报错截图请见：
![image](https://user-images.githubusercontent.com/5511351/121457722-b4e6a500-c9da-11eb-9459-46d0ba37e796.png)

**Comment by hongch911** [comment]
wireshark v2.x版本，请使用wireshark2分支。
